project/Clase/urls.py
from django.urls import path

from . import views

app_name = "clase"

urlpatterns = [
    path("", views.home, name="home"),
    path("localidad/create/", views.LocalidadCreate.as_view(), name="localidad_create"),
    path("localidad/list/", views.LocalidadList.as_view(), name="localidad_list"),
    path("localidad/detail/<int:pk>", views.LocalidadDetail.as_view(), name="localidad_detail"),
    path("localidad/update/<int:pk>", views.LocalidadUpdate.as_view(), name="localidad_update"),
    path("localidad/delete/<int:pk>", views.LocalidadDelete.as_view(), name="localidad_delete"),
    path('index_staff/', views.index_staff, name='index_staff'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('agregar_vendedor/', views.agregar_vendedor, name='agregar_vendedor'),
    path('agregar_pedido/', views.agregar_pedido, name='agregar_pedido'),
    path('about_me/', views.about_me, name='about_me'),
    path('mis_datos/', views.mis_datos, name='mis_datos'),
    path('mis-datos/editar/', views.mis_datos_editar, name='mis_datos_editar'),
]

urlpatterns += [
    path("clase/list/", views.SucursalList.as_view(), name="sucursal_list"),
    path("clase/create/", views.SucursalCreate.as_view(), name="sucursal_create"),
    path("clase/detail/<int:pk>", views.SucursalDetail.as_view(), name="sucursal_detail"),
    path("clase/update/<int:pk>", views.SucursalUpdate.as_view(), name="sucursal_update"),
    path("clase/delete/<int:pk>", views.SucursalDelete.as_view(), name="sucursal_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clase/', include("clase.urls")),
    path('', include("core.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/Clase/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Localidad(models.Model):
    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name="descripción")

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = "localidad"
        verbose_name_plural = "localidades"

class Sucursal(models.Model):
    localidad = models.ForeignKey(
        Localidad, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="localidad"
    )
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")
    fecha_actualizacion = models.DateTimeField(
        null=True, blank=True, default=timezone.now, editable=False, verbose_name="fecha de actualización"
    )

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = "sucursal"
        verbose_name_plural = "sucursales"

class Cliente(models.Model):
    nombre = models.CharField(max_length=100, null=True, blank=True)
    direccion = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.nombre
    
class Vendedor(models.Model):
    nombre = models.CharField(max_length=100)
    edad = models.IntegerField(default=0)
    
    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    codigo = models.PositiveIntegerField(unique=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True, blank=True, related_name='pedidos_cliente')
    vendedor = models.ForeignKey(Vendedor, on_delete=models.SET_NULL, null=True, blank=True, related_name='pedidos_vendedor')
    fecha_actualizacion = models.DateField(
        null=True, blank=True, default=timezone.now, editable=False, verbose_name="fecha de actualización"
    )
 
    def __str__(self):
        return str(self.codigo)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def __str__(self):
        return self.user.username

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/media/default.jpg'

project/Clase/forms.py
from django import forms
from . import models
from .models import UserProfile

class LocalidadForm(forms.ModelForm):
    class Meta:
        model = models.Localidad
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }


class SucursalForm(forms.ModelForm):
    class Meta:
        model = models.Sucursal
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "telefono": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "localidad_id": forms.Select(attrs={"class": "form-control"}),
            "fecha_actualizacion": forms.TextInput(attrs={"class": "form-control"}),
        }

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nombre', 'direccion', 'avatar']

project/Clase/views.py
from .models import Sucursal, Cliente, Vendedor, Pedido
from django.db import IntegrityError
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from . import forms, models
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from .forms import UserProfileForm
from .models import UserProfile
from django.contrib import messages
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

def home(request):
    return render(request, "clase/index.html")

class LocalidadList(ListView):
    model = models.Localidad

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Localidad.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Localidad.objects.all()
        return object_list

class LocalidadCreate(CreateView):
    model = models.Localidad
    form_class = forms.LocalidadForm
    success_url = reverse_lazy("clase:home")

class LocalidadUpdate(UpdateView):
    model = models.Localidad
    form_class = forms.LocalidadForm
    success_url = reverse_lazy("clase:localidad_list")

class LocalidadDetail(DetailView):
    model = models.Localidad

class LocalidadDelete(DeleteView):
    model = models.Localidad
    success_url = reverse_lazy("clase:localidad_list")

class SucursalList(ListView):
    model = models.Sucursal

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Sucursal.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Sucursal.objects.all()
        return object_list


class SucursalCreate(CreateView):
    model = models.Sucursal
    form_class = forms.SucursalForm
    success_url = reverse_lazy("clase:home")


class SucursalUpdate(UpdateView):
    model = models.Sucursal
    form_class = forms.SucursalForm
    success_url = reverse_lazy("clase:sucursal_list")


class SucursalDetail(DetailView):
    model = models.Sucursal


class SucursalDelete(DeleteView):
    model = models.Sucursal
    success_url = reverse_lazy("clase:sucursal_list")

def agregar_cliente(request):
    if request.method == 'POST':
        nombre_cliente = request.POST.get('nombre')
        direccion_cliente = request.POST.get('direccion')
        email_cliente = request.POST.get('email')
        edad_cliente = request.POST.get('edad')

        if Cliente.objects.filter(nombre=nombre_cliente).exists():
            messages.error(request, 'Ya existe un cliente con este nombre')
            return render(request, 'core/index.html', {'mensaje': 'Ya existe un cliente con este nombre'})

        Cliente.objects.create(nombre=nombre_cliente, direccion=direccion_cliente, email=email_cliente, edad=edad_cliente)

        return redirect('clase:agregar_pedido')
    else:
        return render(request, 'core/base.html')
    
def agregar_vendedor(request):
    if request.method == 'POST':
        nombre_vendedor = request.POST.get('vendedor')
        edad_vendedor = request.POST.get('edad')

        if Vendedor.objects.filter(nombre=nombre_vendedor).exists():
            messages.error(request, 'Ya existe un vendedor con este nombre')
            return render(request, 'core/index_staff.html', {'mensaje': 'Ya existe un vendedor con este nombre'})
        
        if nombre_vendedor and edad_vendedor:
            Vendedor.objects.create(nombre=nombre_vendedor, edad=edad_vendedor)
            return redirect('core:home')
        else:
            return render(request, 'core/base.html', {'message': 'El nombre y la edad del vendedor son obligatorios'})
    else:
        return render(request, 'core/base.html')

def agregar_pedido(request):
    if request.method == 'POST':
        codigo = request.POST.get('codigo')
        sucursal_id = request.POST.get('sucursales')
        vendedor_id = request.POST.get('vendedores')
        cliente_id = request.POST.get('clientes')
        
        try:
            sucursal = Sucursal.objects.get(id=sucursal_id)
            vendedor = Vendedor.objects.get(id=vendedor_id)
            cliente = Cliente.objects.get(id=cliente_id)
            
            while Pedido.objects.filter(codigo=codigo).exists():
                messages.error(request, 'Ya existe un pedido con este codigo')
                return render(request, 'core/agregar_pedido.html', {'mensaje': 'Ya existe un pedido con este codigo'})
            
            pedido = Pedido.objects.create(codigo=codigo, sucursal=sucursal, vendedor=vendedor, cliente=cliente)
        except (Sucursal.DoesNotExist, Vendedor.DoesNotExist, Cliente.DoesNotExist):
            error_message = "Uno o más objetos no existen"
            sucursales = Sucursal.objects.all()
            vendedores = Vendedor.objects.all()
            clientes = Cliente.objects.all()
            return render(request, 'core/agregar_pedido.html', {'error_message': error_message, 'sucursales': sucursales, 'vendedores': vendedores, 'clientes': clientes})
        except IntegrityError:
            error_message = "Ya existe un pedido con este código"
            sucursales = Sucursal.objects.all()
            vendedores = Vendedor.objects.all()
            clientes = Cliente.objects.all()
            return render(request, 'core/agregar_pedido.html', {'error_message': error_message, 'sucursales': sucursales, 'vendedores': vendedores, 'clientes': clientes})
        
        return redirect('clase:agregar_pedido')
    
    else:
        sucursales = Sucursal.objects.all()
        vendedores = Vendedor.objects.all()
        clientes = Cliente.objects.all()
        return render(request, 'core/agregar_pedido.html', {'sucursales': sucursales, 'vendedores': vendedores, 'clientes': clientes})
    
def about_me(request):
    return render(request, 'core/about_me.html')

@staff_member_required
def index_staff(request):
    return render(request, 'core/index_staff.html')

@login_required
def mis_datos(request):
    usuario = request.user
    try:
        perfil_usuario = UserProfile.objects.get(user=usuario)
    except UserProfile.DoesNotExist:
        perfil_usuario = None

    return render(request, 'core/mis_datos.html', {'perfil_usuario': perfil_usuario})

@login_required
def mis_datos_editar(request):
    usuario = request.user
    try:
        perfil_usuario = UserProfile.objects.get(user=usuario)
    except UserProfile.DoesNotExist:
        perfil_usuario = None

    if request.method == 'POST':
        if perfil_usuario:
            form = UserProfileForm(request.POST, request.FILES, instance=perfil_usuario)
        else:
            form = UserProfileForm(request.POST, request.FILES)
            
        if form.is_valid():
            perfil_usuario = form.save(commit=False)
            perfil_usuario.user = usuario
            if 'avatar-clear' in form.cleaned_data and perfil_usuario.avatar == 'default.jpg':
                pass
            elif 'avatar-clear' in form.cleaned_data:   
                perfil_usuario.avatar = None
            elif not request.FILES and not perfil_usuario.avatar:
                perfil_usuario.avatar = 'default.jpg'
            perfil_usuario.save()
            return redirect('clase:mis_datos')
    else:
        if perfil_usuario:
            form = UserProfileForm(instance=perfil_usuario)
        else:
            perfil_usuario = UserProfile(user=usuario, avatar='default.jpg')
            perfil_usuario.save()
            form = UserProfileForm(instance=perfil_usuario)

        if 'avatar-clear' in form.fields:
            del form.fields['avatar-clear']

    return render(request, 'core/mis_datos_editar.html', {'form': form})

project/Clase/templates/clase/index.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        App Sucursales
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por localidades</div>
                <h1 class="masthead-heading text-uppercase">Sucursales</h1>
            </div>
        </header>
        <div class="container my-5">
            <h3 class="pb-3 border-bottom" style="font-size: 30px;">Localidades</h3>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
                <a class="btn btn-primary btn-lg me-md-2" href="{% url 'clase:localidad_create' %}" role="button">Agregar Localidad</a>
                <a class="btn btn-outline-primary btn-lg" href="{% url 'clase:localidad_list' %}" role="button">Listar Localidades</a>
            </div>

            <h3 class="pb-3 border-bottom" style="font-size: 30px;">Sucursales</h3>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
                <a class="btn btn-success btn-lg me-md-2" href="{% url 'clase:sucursal_create' %}" role="button">Agregar Sucursal</a>
                <a class="btn btn-outline-success btn-lg" href="{% url 'clase:sucursal_list' %}" role="button">Listar Sucursales</a>
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
                <a class="btn btn-secondary btn-lg" href="{% url 'clase:index_staff' %}" role="button">Volver a Inicio</a>
            </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/localidad_confirm_delete.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Sucursales: Borrar una Localidad de Sucursales
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por localidades</div>
                <h1 class="masthead-heading text-uppercase">Sucursales</h1>
            </div>
        </header>
        <div class="container my-5">
        <h1 style="font-size: 30px;">Eliminar localidad</h1>
        <p class="fst-italic" style="font-size: 24px;">¿Confirma eliminar "{{ object.nombre }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-lg text-uppercase">Confirmar</button>
        </form>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase mt-2">Volver al inicio de Sucursal</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/localidad_detail.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Sucursales: Detalle de una Localidad de Sucursal
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por localidades</div>
                <h1 class="masthead-heading text-uppercase">Sucursales</h1>
            </div>
        </header>
        <div class="container my-5">
        <h1 style="font-size: 30px;">Localidad</h1>
        <ul style="font-size: 24px;">
            <li>Nombre: {{ object.nombre }}</li>
            <li>Descripción: {{ object.descripcion }}</li>
        </ul>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:localidad_list' %}" class="btn btn-primary btn-lg text-uppercase">Volver al inicio de sucursal</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/localidad_list.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Sucursales: Lista de Localidad de Sucursales
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por localidades</div>
                <h1 class="masthead-heading text-uppercase">Sucursales</h1>
            </div>
        </header>
        <div class="container my-5">
            <div class="py-lg-2">
                <form action="{% url 'clase:localidad_list' %}" method="get">
                    <input type="text" name="consulta" class="form-control" style="font-size: 24px;" placeholder="Buscar...">
                </form>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="font-size: 30px;">Localidades</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sucursal in object_list %}
                        <tr>
                            <td style="font-size: 24px;">{{ sucursal.nombre }}</td> 
                            <td>
                                <a class="btn btn-info btn-lg me-1"
                                href="{% url 'clase:localidad_detail' sucursal.id %}">Detalle</a>
                                <a class="btn btn-warning btn-lg me-1"
                                href="{% url 'clase:localidad_update' sucursal.id %}">Editar</a>
                                <a class="btn btn-danger btn-lg"
                                href="{% url 'clase:localidad_delete' sucursal.id %}">Borrar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="fs-3 pb-4">
                <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase">Volver al inicio de Sucursal</a>
            </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/localidad_update.html
    {% extends 'core/base.html' %}
    {% load static %}
    {% block title %}
        Sucursales: Cambiar una Localidad de Sucursales
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por localidades</div>
                <h1 class="masthead-heading text-uppercase">Sucursales</h1>
            </div>
        </header>
        <div class="container my-5">
        <form method="post">
            {% csrf_token %}
            <table style="font-size: 30px;">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm text-uppercase">Guardar</button>
        </form>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:localidad_list' %}" class="btn btn-secondary btn-sm text-uppercase">Volver</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/producto_form.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Producto: 
        {% if form.instance.pk %}
            Editar
        {% else %}
            Crear
        {% endif %}
        Productos
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por categorias</div>
                <h1 class="masthead-heading text-uppercase">Productos</h1>
            </div>
        </header>
        <div class="container my-5">
        <form method="post">
            {% csrf_token %}
            <table class="table table-striped">
                <h1 style="font-size: 30px;">Agregar producto</h1>
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-lg text-uppercase float-left">Guardar</button>
        </form>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase float-left mt-2">Volver al inicio de Producto</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/productocategoria_confirm_delete.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Productos: Borrar una Categoría de Productos
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por categorias</div>
                <h1 class="masthead-heading text-uppercase">Productos</h1>
            </div>
        </header>
        <div class="container my-5">
        <h1 style="font-size: 30px;">Eliminar categoria</h1>
        <p class="fst-italic" style="font-size: 24px;">¿Confirma eliminar "{{ object.nombre }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-lg text-uppercase">Confirmar</button>
        </form>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase mt-2">Volver al inicio de Producto</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/productocategoria_detail.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Productos: Detalle de una Categoría de Producto
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por categorias</div>
                <h1 class="masthead-heading text-uppercase">Productos</h1>
            </div>
        </header>
        <div class="container my-5">
        <h1 style="font-size: 30px;">Categoria</h1>
        <ul style="font-size: 24px;">
            <li>Nombre: {{ object.nombre }}</li>
            <li>Descripción: {{ object.descripcion }}</li>
        </ul>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:productocategoria_list' %}" class="btn btn-primary btn-lg text-uppercase">Volver al inicio de producto</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/productocategoria_form.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Producto: 
        {% if form.instance.pk %}
            Editar
        {% else %}
            Crear
        {% endif %}
        Categoría de Productos
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por categorias</div>
                <h1 class="masthead-heading text-uppercase">Productos</h1>
            </div>
        </header>
        <div class="container my-5">
        <h3  style="font-size: 30px;">Agregar categoria</h3>
        <form method="post">
            {% csrf_token %}
            <table style="font-size: 24px;">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-lg text-uppercase">Guardar</button>
        </form>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase mt-2">Volver al inicio de Producto</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/productocategoria_list.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Productos: Lista de Categoría de Productos
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por categorias</div>
                <h1 class="masthead-heading text-uppercase">Productos</h1>
            </div>
        </header>
        <div class="container my-5">
            <div class="py-lg-2">
                <form action="{% url 'clase:productocategoria_list' %}" method="get">
                    <input type="text" name="consulta" class="form-control" style="font-size: 24px;" placeholder="Buscar...">
                </form>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="font-size: 30px;">Categorias</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in object_list %}
                        <tr>
                            <td style="font-size: 24px;">{{ producto.nombre }}</td> 
                            <td>
                                <a class="btn btn-info btn-lg me-1"
                                href="{% url 'clase:productocategoria_detail' producto.id %}">Detalle</a>
                                <a class="btn btn-warning btn-lg me-1"
                                href="{% url 'clase:productocategoria_update' producto.id %}">Editar</a>
                                <a class="btn btn-danger btn-lg"
                                href="{% url 'clase:productocategoria_delete' producto.id %}">Borrar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="fs-3 pb-4">
                <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase">Volver al inicio de Producto</a>
            </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/productocategoria_update.html
    {% extends 'core/base.html' %}
    {% load static %}
    {% block title %}
        Productos: Cambiar una Categoría de Productos
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por categorias</div>
                <h1 class="masthead-heading text-uppercase">Productos</h1>
            </div>
        </header>
        <div class="container my-5">
        <form method="post">
            {% csrf_token %}
            <table style="font-size: 30px;">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm text-uppercase">Guardar</button>
        </form>
        <div class="fs-3 pb-4">
            <a href="{% url 'clase:productocategoria_list' %}" class="btn btn-secondary btn-sm text-uppercase">Volver</a>
        </div>
        </div>
    {% endblock content %}

project/Clase/templates/clase/sucursal_confirm_delete.html
    {% extends 'core/base.html' %}
    {% load static %}

    {% block title %}
        Sucursales: Borrar un Sucursal
    {% endblock title %}

    {% block content %}
        {% include 'core/components/navbar.html' %}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crealos, editalos o borralos por localidades</div>
                <h1 class="masthead-heading text-uppercase">Sucursales</h1>
            </div>
        </header>
        <div class="container my-5">
            <h1 style="font-size: 30px;">Eliminar sucursal</h1>
            <p class="fs-3 fst-italic">¿Confirma eliminar "{{ object.nombre }}"?</p>

            <form method="post" class="mt-4">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-lg text-uppercase">Confirmar</button>
            </form>
            <div class="fs-3 pb-4 mt-2">
                <a href="{% url 'clase:home' %}" class="btn btn-secondary btn-lg text-uppercase">Volver al inicio de Sucursal</a>
            </div>
        </div>
    {% endblock content %}