project/Clase/urls.py
from django.urls import path

from . import views

app_name = "clase"

urlpatterns = [
    path("", views.home, name="home"),
    path("localidad/create/", views.LocalidadCreate.as_view(), name="localidad_create"),
    path("localidad/list/", views.LocalidadList.as_view(), name="localidad_list"),
    path("localidad/detail/<int:pk>", views.LocalidadDetail.as_view(), name="localidad_detail"),
    path("localidad/update/<int:pk>", views.LocalidadUpdate.as_view(), name="localidad_update"),
    path("localidad/delete/<int:pk>", views.LocalidadDelete.as_view(), name="localidad_delete"),
    path('index_staff/', views.index_staff, name='index_staff'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('agregar_vendedor/', views.agregar_vendedor, name='agregar_vendedor'),
    path('agregar_pedido/', views.agregar_pedido, name='agregar_pedido'),
    path('about_me/', views.about_me, name='about_me'),
    path('mis_datos/', views.mis_datos, name='mis_datos'),
    path('mis-datos/editar/', views.mis_datos_editar, name='mis_datos_editar'),
]

urlpatterns += [
    path("clase/list/", views.SucursalList.as_view(), name="sucursal_list"),
    path("clase/create/", views.SucursalCreate.as_view(), name="sucursal_create"),
    path("clase/detail/<int:pk>", views.SucursalDetail.as_view(), name="sucursal_detail"),
    path("clase/update/<int:pk>", views.SucursalUpdate.as_view(), name="sucursal_update"),
    path("clase/delete/<int:pk>", views.SucursalDelete.as_view(), name="sucursal_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clase/', include("clase.urls")),
    path('', include("core.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import CustomAuthenticationForm, CustomUserCreationForm


@login_required
def home(request):
    return render(request, "core/index.html")


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('core:home')
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/core/templates/core/components/footer.html
    <footer class="footer py-0">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2024</div>
                <div class="col-lg-8 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Politicas de privacidad</a>
                    <a class="link-dark text-decoration-none" href="#!">Terminos</a>
                </div>
            </div>
        </div>
    </footer>

project/core/templates/core/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <h1 style="color: #ffffff; font-size: 14px;">
            <a class="navbar-brand" href="{% url 'clase:about_me' %}">Diego Drutman</a>
        </h1>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'clase:mis_datos' %}">Mis Datos</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:home' %}">Clientes & Pedidos</a></li>
                    {% if user.is_staff %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'clase:index_staff' %}">Vendedores & Sucursales</a></li
                    {% endif %}
                    <li class="nav-item ms-lg-5">
                        <form action="{% url 'core:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Logout</button>
                        </form>
                    </li>
                    <li class="nav-item ms-lg-3">
                        <span class="nav-link">
                            <i class="fas fa-user"></i>
                            {{ user.username }}
                        </span>
                    </li>
            </ul>            
        </div>
    </div>
</nav>