project/Clase/urls.py
from django.urls import path

from . import views

app_name = "clase"

urlpatterns = [
    path("", views.home, name="home"),
    path("localidad/create/", views.LocalidadCreate.as_view(), name="localidad_create"),
    path("localidad/list/", views.LocalidadList.as_view(), name="localidad_list"),
    path("localidad/detail/<int:pk>", views.LocalidadDetail.as_view(), name="localidad_detail"),
    path("localidad/update/<int:pk>", views.LocalidadUpdate.as_view(), name="localidad_update"),
    path("localidad/delete/<int:pk>", views.LocalidadDelete.as_view(), name="localidad_delete"),
    path('index_staff/', views.index_staff, name='index_staff'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('agregar_vendedor/', views.agregar_vendedor, name='agregar_vendedor'),
    path('agregar_pedido/', views.agregar_pedido, name='agregar_pedido'),
    path('about_me/', views.about_me, name='about_me'),
    path('mis_datos/', views.mis_datos, name='mis_datos'),
    path('mis-datos/editar/', views.mis_datos_editar, name='mis_datos_editar'),
]

urlpatterns += [
    path("clase/list/", views.SucursalList.as_view(), name="sucursal_list"),
    path("clase/create/", views.SucursalCreate.as_view(), name="sucursal_create"),
    path("clase/detail/<int:pk>", views.SucursalDetail.as_view(), name="sucursal_detail"),
    path("clase/update/<int:pk>", views.SucursalUpdate.as_view(), name="sucursal_update"),
    path("clase/delete/<int:pk>", views.SucursalDelete.as_view(), name="sucursal_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clase/', include("clase.urls")),
    path('', include("core.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import CustomAuthenticationForm, CustomUserCreationForm


@login_required
def home(request):
    return render(request, "core/index.html")


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('core:home')
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/core/templates/core/about_me.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
{% endblock title %}

{% block content %}
    {% include 'core/components/navbar.html' %}
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Un poco de mi y de esta aplicacion WEB</div>
            <div class="masthead-heading text-uppercase">About Me</div> 
        </div>
    </header>
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2 class="text-center">Acerca de mí</h2>
                    <p class="lead">Programador Trainee Python.</p>
                    <p>Soy Diego Drutman, desarrollador backend python incursionando en la creación de experiencias digitales con un enfoque especial en tecnologías como Django. Tengo algo de experiencia en desarrollo frontend, utilizando HTML, CSS, y JavaScript.</p>
                    <p>Me encanta trabajar en proyectos desafiantes y aprender nuevas tecnologías para mejorar mis habilidades. Siempre estoy buscando oportunidades para colaborar en proyectos interesantes y llevar adelante ideas de desarrollo.</p>
                    <p class="lead">Pagina CoderHouse Django.</p>
                    <p>Esta aplicación web está diseñada para gestionar pedidos utilizando dos tipos de acceso. Permite la personalización de perfiles, así como la adición de clientes, vendedores y sucursales por localidad. Finalmente, se puede generar un pedido. </p> 
                </div>
            </div>
        </div>
    </section>
    {% endblock content %}

project/core/templates/core/agregar_pedido.html
{% extends 'core/base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
    {% include 'core/components/navbar.html' %}
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Generalo y guardalo directamente en nuestra base de datos</div>
            <div class="masthead-heading text-uppercase">Pedidos</div>
        </div>
    </header>
    <section class="page-section bg-light" id="pedido">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Carga el Pedido</h2>
                <h3 class="section-subheading text-muted mb-4">Completa los campos para agregar un nuevo pedido.</h3>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <form id="add-pedido-form" action="{% url 'clase:agregar_pedido' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input class="form-control {% if mensaje %} is-invalid {% endif %}" id="codigo" name="codigo" type="text" placeholder="Codigo *" required="required" />
                                    {% if mensaje %}
                                        <div class="invalid-feedback">
                                            {{ mensaje }}
                                        </div>
                                    {% endif %}
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select class="form-select" id="sucursales" name="sucursales" aria-label="Seleccionar sucursal" required="required">
                                        <option selected disabled>Selecciona un sucursal</option>
                                        {% for sucursal in sucursales %}
                                            <option value="{{ sucursal.id }}">{{ sucursal.nombre }} ({{ sucursal.localidad }})</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select class="form-select" id="vendedores" name="vendedores" aria-label="Seleccionar vendedor" required="required">
                                        <option selected disabled>Selecciona un vendedor</option>
                                        {% for vendedor in vendedores %}
                                            <option value="{{ vendedor.id }}">{{ vendedor.nombre }} ({{ vendedor.edad }})</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select class="form-select" id="clientes" name="clientes" aria-label="Seleccionar clientes" required="required">
                                        <option selected disabled>Selecciona un cliente</option>
                                        {% for cliente in clientes %}
                                            <option value="{{ cliente.id }}">{{ cliente.nombre }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center mt-4">
                                <div id="success"></div>
                                <button id="add-pedido-submit" class="btn btn-primary btn-xl text-uppercase" type="submit">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            MI WEB INTERMEDIA
        {% endblock title %}
    </title>
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    {% block content %}
    {% endblock content %}
    <footer class="footer py-4" style="position: relative; bottom: 0; width: 100%;">
        {% include 'core/components/footer.html' %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'core/js/scripts.js' %}"></script>
</body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
{% endblock title %}

{% block content %}
    {% include 'core/components/navbar.html' %}
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Generalo y guardalo directamente en nuestra base de datos</div>
            <div class="masthead-heading text-uppercase">¿Nuevo Cliente?</div>
        </div>
    </header>
    {% if user.is_authenticated %}
    <section class="page-section bg-light" id="cliente">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Ingresa sus datos</h2>
                <h3 class="section-subheading text-muted">Los necesitaremos para realizar el pedido.</h3>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <form id="add-cliente-form" action="{% url 'clase:agregar_cliente' %}" method="POST" class="text-center">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control {% if mensaje %} is-invalid {% endif %}" id="nombre" name="nombre" type="text" placeholder="Nombre completo *" required="required" />
                            {% if mensaje %}
                                <div class="invalid-feedback">
                                    {{ mensaje }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="form-control mt-3" id="direccion" name="direccion" type="text" placeholder="Dirección *" required="required" />
                        </div>
                        <div class="form-group">
                            <input class="form-control mt-3" id="email" name="email" type="email" placeholder="Correo Electrónico *" required="required" />
                        </div>
                        <div class="form-group">
                            <input class="form-control mt-3" id="edad" name="edad" type="number" placeholder="Edad *" required="required" />
                        </div>
                        <button class="btn btn-primary btn-xl text-uppercase mt-3" type="submit">Enviar</button>
                        <p class="mt-3">¿Ya está registrado el cliente? <a href="{% url 'clase:agregar_pedido' %}">Haz clic aquí</a></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
{% endblock content %}

project/core/templates/core/index_staff.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        {{ mensaje }}
    {% endif %}
    {% include 'core/components/navbar.html' %}
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Generalo y guardalo directamente en nuestra base de datos</div>
            <div class="masthead-heading text-uppercase">Staff</div>
             
        </div>
    </header>
    <section class="page-section" id="vendedor">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Agrega un nuevo vendedor</h2>
                <h3 class="section-subheading text-muted">Agrega un vendedor nuevo a la lista.</h3>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <form id="add-vendedor-form" action="{% url 'clase:agregar_vendedor' %}" method="POST" class="text-center">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control {% if mensaje %} is-invalid {% endif %}" id="vendedor" name="vendedor" type="text" placeholder="Nombre *" required="required" />
                            {% if mensaje %}
                                <div class="invalid-feedback">
                                    {{ mensaje }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="form-control mt-3" id="edad" name="edad" type="number" placeholder="Edad *" required="required"/>
                        </div>
                        <button class="btn btn-primary btn-xl text-uppercase mt-3" type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section" id="sucursal">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Ingresa sucursales</h2>
                <h3 class="section-subheading text-muted">Agrega o edita un sucursal de la lista.</h3>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <form id="add-sucursal-form" action="{% url 'clase:home' %}" method="POST" class="text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary btn-xl text-uppercase" type="submit">Agregar sucursal</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
<section class="page-section bg-light" id="pedido">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Login</h2>
                    <h3 class="section-subheading text-muted">Completa los campos para ingresar.</h3>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-7">
                        <form method="post" class="text-center"> 
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="hidden" name="next" value="{% url 'core:home' %}">
                            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                            <a href="{% url 'core:home' %}" class="btn btn-secondary">Cancelar</a>
                        </form>
                        <p class="mt-3 text-center">¿No tienes una cuenta? <a href="{% url 'core:register' %}">Regístrate aquí</a>.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

project/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %}
    Logout
{% endblock %}

{% block content %}
    <section class="page-section bg-light" id="pedido">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center">
                        <h2 class="section-heading text-uppercase">Has cerrado sesión</h2>
                        <h3 class="section-subheading text-muted">¡Hasta luego!</h3>
                        <a href="{% url 'core:home' %}" class="btn btn-secondary">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

project/core/templates/core/mis_datos.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        {{ mensaje }}
    {% endif %}
    {% include 'core/components/navbar.html' %}
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Generalo y guardalo directamente en nuestra base de datos</div>
            <div class="masthead-heading text-uppercase">Mis Datos</div>
        </div>
    </header>
    {% if perfil_usuario %}
    <section class="page-section bg-light" id="cliente">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Datos de tu usuario</h2>
                <h3 class="section-subheading text-muted">Están asociados a tu ingreso y tu perfil.</h3>
            </div>
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-4">
                    <div class="text-center">
                        {% if perfil_usuario.avatar %}
                        <img src="{{ perfil_usuario.avatar.url }}" alt="Avatar" class="img-fluid rounded-circle mb-2" style="height: 200px;">
                    {% else %}
                        <img src="{% static 'default.jpg' %}" alt="Avatar Predeterminado" class="img-fluid rounded-circle mb-2" style="height: 200px;">
                    {% endif %}                    
                    </div>
                </div>
                <div class="col-lg-4">
                    <ul>
                        <li>
                            <span class="font-weight-bold" style="font-size: 18px;">Nombre:</span>
                            <span class="font-size-large" style="font-size: 22px;">{{ perfil_usuario.nombre }}</span>
                        </li>
                        <li>
                            <span class="font-weight-bold" style="font-size: 18px;">Dirección:</span>
                            <span class="font-size-large" style="font-size: 22px;">{{ perfil_usuario.direccion }}</span>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <div class="text-center mt-5 mt-lg-20">
                        <a href="{% url 'clase:mis_datos_editar' %}" class="btn btn-primary btn-xl text-uppercase" type="submit">Editar</a>
                    </div>
                </div>                                        
            </div>
        </div>
    </section>
    {% else %}
    <section class="page-section bg-light" id="cliente">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Aun no has configurado tu perfil.</h2>
                <h3 class="section-subheading text-muted">Recomendamos hacerlo lo antes posible para una mas facil identificacion.</h3>
                <a href="{% url 'clase:mis_datos_editar' %}" class="btn btn-primary btn-xl text-uppercase mt-3">Agregar datos</a>
            </div>
        </div>
    </section>
    {% endif %}
{% endblock content %}

project/core/templates/core/mis_datos_editar.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        {{ mensaje }}
    {% endif %}
    {% include 'core/components/navbar.html' %}
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Generalo y guardalo directamente en nuestra base de datos</div>
            <div class="masthead-heading text-uppercase">Datos</div>
             
        </div>
    </header>
    <section class="page-section bg-light" id="cliente">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Edita tus datos personales</h2>
                <h3 class="section-subheading text-muted">Los necesitaremos para poder identificarte.</h3>
            </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <form method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-xl text-uppercase mt-3">Guardar Cambios</button>
                </form>                
            </div>
        </div>
    </div>
{% endblock content %}

project/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}
    Registro
{% endblock %}

{% block content %}
    <section class="page-section bg-light" id="registro">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center">
                        <h2 class="section-heading text-uppercase">Registro de usuario</h2>
                        <h3 class="section-subheading text-muted">Completa los campos para registrarte.</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Registrar nuevo usuario</button>
                    </form>
                    <p class="mt-3 text-center">Ya tienes una cuenta? <a href="{% url 'core:login' %}">Ingresa aquí</a>.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}